// 自動生成された楽曲データ
const SONG_DATABASE = [
  {"title": "Siny Smily Story (2022 ver.)", "time": "1:40", "bonus": 6},
  {"title": "青春アーカイブ", "time": "1:50", "bonus": 11},
  {"title": "夢見る空へ", "time": "1:42", "bonus": 7},
  {"title": "キラメキライダー☆", "time": "1:49"},
  {"title": "Dreaming Days", "time": "1:43"},
  {"title": "あすいろClearSky", "time": "1:48"},
  {"title": "Prism Melody", "time": "1:50"},
  {"title": "Our Bright Parade", "time": "2:17"},
  {"title": "Capture the Moment", "time": "1:57"},
  {"title": "Color Rise Harmony", "time": "2:39", "bonus": 37},
  {"title": "Ridin' on Dreams", "time": "2:39"},
  {"title": "夢色ワンダー", "time": "2:37"},
  {"title": "ギミギミエンターテイメント", "time": "2:32"},
  {"title": "Dream☆Story", "time": "2:00"},
  {"title": "スタースタースタート", "time": "2:09"},
  {"title": "リルビ", "time": "2:22"},
  {"title": "鬼ノ宴", "time": "2:12"},
  {"title": "ω猫", "time": "2:17"},
  {"title": "いのち(2024 ver.)", "time": "1:49"},
  {"title": "flower rhapsody", "time": "1:57"},
  {"title": "DAI DAI DAI ファンタジスタ", "time": "2:00"},
  {"title": "きゅんきゅんみこきゅんきゅん♡", "time": "2:24"},
  {"title": "Stellar Stellar", "time": "2:18"},
  {"title": "ビビデバ", "time": "2:02"},
  {"title": "GHOST", "time": "1:58"},
  {"title": "シャルイース", "time": "2:26"},
  {"title": "気まぐれメルシィ", "time": "2:29"},
  {"title": "ブタサンダー", "time": "2:16"},
  {"title": "感触", "time": "2:24"},
  {"title": "Inifinity (Remastered)", "time": "2:02"},
  {"title": "シル・ヴ・プレジデント", "time": "1:57"},
  {"title": "SUPERNOVA", "time": "1:58"},
  {"title": "KINGWORLD", "time": "2:08"},
  {"title": "Say!ファンファーレ!", "time": "1:47"},
  {"title": "ばーちゃらぶ", "time": "2:35"},
  {"title": "同担☆拒否", "time": "2:24"},
  {"title": "美少女戦士まつりみっとZero", "time": "1:56"},
  {"title": "宵の余、良い！", "time": "1:40"},
  {"title": "グッバイ宣言", "time": "2:07"},
  {"title": "万歳☆満開", "time": "2:16"},
  {"title": "NoDistance", "time": "2:32"},
  {"title": "妄想税", "time": "1:58"},
  {"title": "ぷ・れ・あ・で・す！", "time": "1:36"},
  {"title": "どぅーまいべすと！", "time": "1:43"},
  {"title": "ホットダック！", "time": "2:16"},
  {"title": "Howling", "time": "1:40"},
  {"title": "Colorful Universe", "time": "2:00"},
  {"title": "夏宿り", "time": "1:54"},
  {"title": "夜行通信", "time": "2:24"},
  {"title": "ナイトループ", "time": "2:14"},
  {"title": "もぐもぐYUMMY！", "time": "2:02"},
  {"title": "ネコカブリーナ", "time": "2:13"},
  {"title": "毒の王子さま", "time": "2:26"},
  {"title": "カミサマ・ネコサマ", "time": "2:19"},
  {"title": "Doggy god's street", "time": "2:07"},
  {"title": "唱", "time": "1:41"},
  {"title": "ころねの最凶天災☆わんだふぉー♡わーるど", "time": "1:44"},
  {"title": "ぺこらんだむぶれいん!", "time": "1:53"},
  {"title": "全人類　兎化計画！", "time": "2:21"},
  {"title": "全力ジャンピング！", "time": "1:37"},
  {"title": "怪物", "time": "2:15"},
  {"title": "UNDEAD", "time": "1:44"},
  {"title": "ぎゅーどんかーにばる！", "time": "1:56"},
  {"title": "寝起きヤシの木", "time": "1:56"},
  {"title": "ほめのび", "time": "2:26"},
  {"title": "Ahoy!! 我ら宝鐘海賊団☆", "time": "1:48"},
  {"title": "美少女無罪♡パイレーツ", "time": "1:40"},
  {"title": "幽霊船戦", "time": "2:12"},
  {"title": "My song", "time": "2:07"},
  {"title": "What an amazing swing", "time": "2:08"},
  {"title": "恋愛サーキュレーション", "time": "1:30"},
  {"title": "Palette", "time": "2:33"},
  {"title": "-ERROR", "time": "2:26"},
  {"title": "FACT", "time": "2:20"},
  {"title": "守護ってルーナイト", "time": "1:51"},
  {"title": "ふわふわ時間", "time": "2:10"},
  {"title": "天たこ観測", "time": "2:11"},
  {"title": "明日への境界線", "time": "2:13"},
  {"title": "勇者", "time": "1:48"},
  {"title": "ねねねねねねねね！大爆走", "time": "2:02"},
  {"title": "ちゅ、多様性", "time": "2:03"},
  {"title": "Lioness' Pride", "time": "2:00"},
  {"title": "ノンブレス・オブリージュ", "time": "2:10"},
  {"title": "ぽ", "time": "2:21"},
  {"title": "エンヴィーベイベー", "time": "2:15"},
  {"title": "神っぽいな", "time": "1:47"},
  {"title": "興味ないよ", "time": "2:09"},
  {"title": "QUEEN", "time": "2:21"},
  {"title": "オーバード", "time": "1:52"},
  {"title": "フクロウさん", "time": "2:06"},
  {"title": "WAO!!(2025 ver.)", "time": "2:39"},
  {"title": "God knows...", "time": "2:40"},
  {"title": "いろはすてっぷ！", "time": "2:10"},
  {"title": "きゅうくらりん", "time": "2:06"},
  {"title": "ALiCE&u", "time": "2:10"},
  {"title": "Snow halatioin", "time": "1:56"},
  {"title": "1:15 AM", "time": "2:27"},
  {"title": "High Tide", "time": "2:10"},
  {"title": "FIRE BIRD", "time": "2:16"},
  {"title": "Q&A=E", "time": "2:24"},
  {"title": "エイリアンエイリアン", "time": "2:19"},
  {"title": "Here I am", "time": "2:28"},
  {"title": "JOLLIE JOLLIE", "time": "1:59"},
  {"title": "狂乱 Hey Kids!!", "time": "2:11"},
  {"title": "Oshi Mode ON", "time": "2:09"},
  {"title": "アンリアルヴェイル", "time": "2:03"},
  {"title": "マーシャル・マキシマイザー", "time": "2:01"},
  {"title": "Gate Open: START!", "time": "2:25"},
  {"title": "うっせぇわ", "time": "2:14"},
  {"title": "You're Mine", "time": "2:30"},
  {"title": "可愛くてごめん", "time": "2:04"},
  {"title": "brave heart", "time": "1:49"},
  {"title": "dahlah.", "time": "2:15"},
  {"title": "Backseat", "time": "2:29"},
  {"title": "Mantra Hujan", "time": "1:50"},
  {"title": "Overdose", "time": "2:08"},
  {"title": "HELP!!", "time": "2:11"},
  {"title": "失礼しますが、RIP♡", "time": "1:31"},
  {"title": "DEAD BEATS", "time": "2:00"},
  {"title": "LET'S JUST CRASH", "time": "1:52"},
  {"title": "NIGHTBREAK", "time": "2:06"},
  {"title": "SPARKS", "time": "1:44"},
  {"title": "ヴァンパイア", "time": "2:01"},
  {"title": "VIOLET", "time": "2:16"},
  {"title": "ないない", "time": "2:12"},
  {"title": "星屑カプセル", "time": "1:57"},
  {"title": "アイドル", "time": "2:06"},
  {"title": "Carbonated Love", "time": "1:58"},
  {"title": "TwiLight", "time": "2:00"},
  {"title": "Daydream", "time": "1:37"},
  {"title": "マフィア", "time": "2:14"},
  {"title": "PSYCHO", "time": "1:35"},
  {"title": "Los! Los! Los!", "time": "2:14"},
  {"title": "Monsters and Men", "time": "2:21"},
  {"title": "強風オールバック", "time": "2:15"},
  {"title": "プリズムの魔法", "time": "2:19"},
  {"title": "鏡面の波", "time": "1:49"},
  {"title": "Say My Name", "time": "2:17"},
  {"title": "雪の華", "time": "2:08"},
  {"title": "Lifetime Showtime", "time": "2:08"},
  {"title": "キュートなカノジョ", "time": "2:11"},
  {"title": "Born to be \"BAU\"DOL☆★", "time": "2:32"},
  {"title": "Let Me Be With You", "time": "1:48"},
  {"title": "GREATEST", "time": "2:05"},
  {"title": "奏（かなで）", "time": "2:46"},
  {"title": "You & 合図", "time": "2:37"},
  {"title": "今日も大天才っ！", "time": "1:52"},
  {"title": "チェリーポップ", "time": "2:22"},
  {"title": "JAPANの美術史♪お・ぼ・え・ま・SHOW！", "time": "2:14"},
  {"title": "ピ ピカソ", "time": "2:24"},
  {"title": "Countach", "time": "2:24"},
  {"title": "ツッパリHigh School Rock'n Roll(登校編)", "time": "2:12"},
  {"title": "Myth or Treat", "time": "2:04"},
  {"title": "Secret Garden", "time": "2:17"},
  {"title": "BLUE CLAPPER", "time": "2:08"},
  {"title": "常夜リペイント", "time": "1:56"},
  {"title": "プライダルドリーム", "time": "2:06"},
  {"title": "Our Promise", "time": "2:12"},
  {"title": "Rebellion", "time": "1:53"},
  {"title": "HI-15", "time": "1:53"},
  {"title": "Slap by Step", "time": "2:09"},
  {"title": "save our hearts", "time": "2:16"},
  {"title": "瞬間ハートビート", "time": "2:11"},
  {"title": "気分上々↑↑", "time": "2:18"},
  {"title": "We are GAMERS !!!!", "time": "2:46"},
  {"title": "刹那ティックコード", "time": "1:45"},
  {"title": "Suspect", "time": "1:57"},
  {"title": "なかま歌", "time": "2:11"},
  {"title": "Wicked feat. Mori Calliope", "time": "2:04"},
  {"title": "おにけもだんす", "time": "2:26"},
  {"title": "地獄で会おうぜ！ スバちょこるなたん", "time": "2:24"},
  {"title": "ORANGE PARADE feat.戌神ころね", "time": "2:03"},
  {"title": "III", "time": "2:26"},
  {"title": "ししわたクッキング feat.獅白ぼたん", "time": "1:59"},
  {"title": "回レ！雪月花", "time": "2:21"},
  {"title": "デビルじゃないもん", "time": "2:12"},
  {"title": "ハオ", "time": "2:06"},
  {"title": "わたしの一番かわいいところ", "time": "2:26"},
  {"title": "メギツネ", "time": "2:15"},
  {"title": "ヒャダインのじょーじょーゆーじょー", "time": "2:13"},
  {"title": "また傷に触れる", "time": "1:54"},
  {"title": "青く在れ", "time": "2:05"},
  {"title": "みっころね×しょうたいむ!!", "time": "2:06"},
  {"title": "再会", "time": "2:10"},
  {"title": "神のまにまに", "time": "2:10"},
  {"title": "い〜やい〜やい〜や", "time": "2:23"},
  {"title": "選んでくれてありがとう。", "time": "1:50"},
  {"title": "六兆年と一夜物語", "time": "2:35"},
  {"title": "オレンジ", "time": "2:13"},
  {"title": "UFO", "time": "1:44"},
  {"title": "爆夏!!トロピカバケーション", "time": "2:16"},
  {"title": "Bling-Bang-Bang-Born", "time": "2:00"},
  {"title": "シュガーラッシュ", "time": "2:14"}
];
